apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: piku
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: docker.io/pengdol2/pikubernetes-backend:v0.3
        ports:
        - containerPort: 8000
        env:
        - name: googleSearchKey
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: googleSearchKey
        - name: googleCSEId
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: googleCSEId
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DATABASE_URL
        - name: gptApiKey
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: gptApiKey
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: piku
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000



