namespace: pikubernetes

postgresql:
  image: postgres:14
  username: "postgres"
  password: "1234"
  database: "piku"
  pgdata: /var/lib/postgresql/data/pgdata
  mountpath: /var/lib/postgresql/data
  port: 5432
  targetPort: 5432

backend:
  image: docker.io/rabo8497/rabo-back:v1.0
  googleSearchKey: ${googleSearchKey}
  googleCSEId: ${googleCSEId}
  databaseUrl: ${DATABASE_URL}
  gptApiKey: ${gptApiKey}
  port: 8000
  targetPort: 8000
  protocol: TCP

frontend:
  image: docker.io/rabo8497/rabo-front:v1.0
  backendAddress: ${backendAddress}
  port: 80
  targetPort: 80
  protocol: TCP
