apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_USER: "{{ .Values.postgresql.username }}"
  POSTGRES_PASSWORD: "{{ .Values.postgresql.password }}"
  POSTGRES_DB: "{{ .Values.postgresql.database }}"
  pg_hba.conf: |
    # TYPE  DATABASE    USER    ADDRESS   METHOD
    local all   all   trust
    host  all   all   127.0.0.1/32    trust
    host  all   all   0.0.0.0/0   md5
    host    all             all             ::1/128                 trust
    local   replication     all                                     trust
    host    replication     all             127.0.0.1/32            trust
    host    replication     all             ::1/128                 trust

    host all all all scram-sha-256
  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 100
    port = 5432
