apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  googleSearchKey: {{ .Values.backend.googleSearchKey | b64enc }}
  googleCSEId: {{ .Values.backend.googleCSEId | b64enc }}
  DATABASE_URL: {{ .Values.backend.databaseUrl | b64enc }}
  gptApiKey: {{ .Values.backend.gptApiKey | b64enc }}
